In [28]:
import pandas as pd
import tensorflow
from tensorflow.python.keras.models import *
from tensorflow.python.keras.layers import *
import math
import numpy as np
from numpy import linalg as LA
from sklearn.metrics import mean_squared_error

In [29]:
# url = 'https://raw.githubusercontent.com/ariya01/Kelas-DeepLearning-TimeSeries/master/historical_weather.csv'
df = pd.read_csv("historical_weather.csv") # Load DATASET
df =df.loc[df["point"]==1] # Load Point 1
df = df.drop(['point','prediction_date'], axis=1) # Drop Column
trainrow=df.shape[0]*80/100 #Split
train = df[:int(trainrow)] 
train.head()

wind_speed_100m  wind_direction_100m  temperature  air_density  pressure  \
0             13.6                210.3          9.8         1.17     952.2   
1             13.6                210.0          9.8         1.17     951.6   
2             13.6                209.8          9.8         1.17     951.1   
3             13.6                209.6          9.8         1.17     950.5   
4             13.8                218.2          9.9         1.17     950.7   

   precipitation  wind_gust  radiation  wind_speed  wind_direction  
0            0.0       19.4       10.0         7.0           203.7  
1            0.0       19.6       16.8         7.0           204.0  
2            0.0       19.9       19.9         7.0           204.3  
3            0.0       20.1       20.0         7.1           204.6  
4            0.0       19.0       17.9         7.1           212.6

In [5]:
test = df[-int(df.shape[0]-trainrow):] #Split
test.head()

wind_speed_100m  wind_direction_100m  temperature  air_density  \
12116              8.9                 48.8         13.9         1.15   
12117              8.6                 47.7         16.4         1.14   
12118              8.1                 45.7         17.7         1.14   
12119              7.6                 43.6         19.0         1.13   
12120              6.0                 30.4         20.6         1.12   

       pressure  precipitation  wind_gust  radiation  wind_speed  \
12116     948.3            0.3       10.6      252.6         5.0   
12117     948.1            0.3        9.2      410.0         5.4   
12118     947.9            0.3        8.3      552.0         5.3   
12119     947.6            0.3        7.5      640.6         5.1   
12120     946.9            0.0        5.7      625.0         4.2   

       wind_direction  
12116            46.9  
12117            46.0  
12118            43.5  
12119            41.0  
12120            27.5

In [18]:
y = train['precipitation'] #Class
x = train.drop(['precipitation'], axis=1)
y = y.values

x = x.values
x.shape

(12115, 9)

In [19]:
x.shape[1]
for i in range(x.shape[1]):
    x[:,i] = x[:,i]/LA.norm(x[:,i])

x = x.reshape((x.shape[0],1,x.shape[1]))
x[:5]

array([[[0.0202986 , 0.00957772, 0.00714166, 0.00900651, 0.0090076 ,
         0.0234674 , 0.00030209, 0.01975978, 0.00939319]],

       [[0.0202986 , 0.00956406, 0.00714166, 0.00900651, 0.00900193,
         0.02370934, 0.00050751, 0.01975978, 0.00940703]],

       [[0.0202986 , 0.00955495, 0.00714166, 0.00900651, 0.0089972 ,
         0.02407223, 0.00060116, 0.01975978, 0.00942086]],

       [[0.0202986 , 0.00954584, 0.00714166, 0.00900651, 0.00899152,
         0.02431417, 0.00060418, 0.02004206, 0.0094347 ]],

       [[0.02059711, 0.00993751, 0.00721453, 0.00900651, 0.00899341,
         0.02298354, 0.00054074, 0.02004206, 0.0098036 ]]])

In [21]:
model = Sequential()
model.add(LSTM(50, input_shape=(x.shape[1], x.shape[2]))) # LSTM Model
model.add(Dense(1))
model.compile(loss='mae', optimizer='adam')

In [22]:
history = model.fit(x, y, epochs=50, batch_size=24, validation_split=0.33, verbose=2, shuffle=False) #Train

Train on 8117 samples, validate on 3998 samples
Epoch 1/50
 - 3s - loss: 0.1324 - val_loss: 0.1247
Epoch 2/50
 - 1s - loss: 0.1323 - val_loss: 0.1248
Epoch 3/50
 - 1s - loss: 0.1320 - val_loss: 0.1246
Epoch 4/50
 - 1s - loss: 0.1319 - val_loss: 0.1248
Epoch 5/50
 - 1s - loss: 0.1318 - val_loss: 0.1252
Epoch 6/50
 - 1s - loss: 0.1317 - val_loss: 0.1247
Epoch 7/50
 - 1s - loss: 0.1317 - val_loss: 0.1250
Epoch 8/50
 - 1s - loss: 0.1317 - val_loss: 0.1246
Epoch 9/50
 - 1s - loss: 0.1317 - val_loss: 0.1250
Epoch 10/50
 - 1s - loss: 0.1317 - val_loss: 0.1249
Epoch 11/50
 - 1s - loss: 0.1317 - val_loss: 0.1245
Epoch 12/50
 - 1s - loss: 0.1316 - val_loss: 0.1245
Epoch 13/50
 - 1s - loss: 0.1317 - val_loss: 0.1246
Epoch 14/50
 - 1s - loss: 0.1317 - val_loss: 0.1246
Epoch 15/50
 - 1s - loss: 0.1317 - val_loss: 0.1245
Epoch 16/50
 - 1s - loss: 0.1317 - val_loss: 0.1246
Epoch 17/50
 - 1s - loss: 0.1317 - val_loss: 0.1246
Epoch 18/50
 - 1s - loss: 0.1317 - val_loss: 0.1250
Epoch 19/50
 - 1s - loss:

In [23]:
test_y = test['precipitation']
test_x = test.drop(['precipitation'], axis=1)
test_x = test_x.values
test_y = test_y.values

for i in range(test_x.shape[1]):
    test_x[:,i] = test_x[:,i]/LA.norm(test_x[:,i])

test_x = test_x.reshape((test_x.shape[0],1,test_x.shape[1]))

In [24]:
yhat = model.predict(test_x)
yhat

array([[5.9921167e-05],
       [6.3847001e-05],
       [6.7091489e-05],
       ...,
       [7.5923323e-05],
       [7.6115291e-05],
       [7.6218188e-05]], dtype=float32)

In [25]:
inv_yhat = yhat[:,0]
inv_yhat

array([5.9921167e-05, 6.3847001e-05, 6.7091489e-05, ..., 7.5923323e-05,
       7.6115291e-05, 7.6218188e-05], dtype=float32)

In [26]:
inv_y = test_y
inv_y


array([0.3, 0.3, 0.3, ..., 0. , 0. , 0. ])

In [27]:
rmse = math.sqrt(mean_squared_error(inv_y, inv_yhat))
print('Test RMSE: %.3f' % rmse)

Test RMSE: 0.284
